/**
 * This class is generated by jOOQ
 */
package by.heap.dao.jooq;


import by.heap.dao.jooq.tables.Films;
import by.heap.dao.jooq.tables.SchemaVersion;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table public.films
	 */
	public static final Films FILMS = by.heap.dao.jooq.tables.Films.FILMS;

	/**
	 * The table public.schema_version
	 */
	public static final SchemaVersion SCHEMA_VERSION = by.heap.dao.jooq.tables.SchemaVersion.SCHEMA_VERSION;
}
