container:
  image: gradle:jdk11

check_task:
  gradle_cache:
    folder: ~/.gradle/caches
  cleanup_before_cache_script:
    - rm -rf ~/.gradle/caches/$GRADLE_VERSION/
    - rm -rf ~/.gradle/caches/transforms-1
    - rm -rf ~/.gradle/caches/journal-1
    - rm -rf ~/.gradle/caches/jars-3/*/buildSrc.jar
    - find ~/.gradle/caches/ -name "*.lock" -type f -delete
  check_script: ./gradlew check
  always:
    junit_artifacts:
      path: "**/test-results/**/*.xml"
      format: junit
