/*
 * This file is generated by jOOQ.
 */
package io.heapy.crm.komodo.store.postgres.tables.references


import io.heapy.crm.komodo.store.postgres.tables.FlywaySchemaHistory
import io.heapy.crm.komodo.store.postgres.tables.Person



/**
 * The table <code>public.flyway_schema_history</code>.
 */
val FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY

/**
 * The table <code>public.person</code>.
 */
val PERSON = Person.PERSON
