/**
 * This class is generated by jOOQ
 */
package by.heap.dao.jooq.tables;


import by.heap.dao.jooq.Keys;
import by.heap.dao.jooq.Public;
import by.heap.dao.jooq.tables.records.FilmsRecord;

import java.sql.Date;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Films extends TableImpl<FilmsRecord> {

	private static final long serialVersionUID = 110319300;

	/**
	 * The reference instance of <code>public.films</code>
	 */
	public static final Films FILMS = new Films();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<FilmsRecord> getRecordType() {
		return FilmsRecord.class;
	}

	/**
	 * The column <code>public.films.code</code>.
	 */
	public final TableField<FilmsRecord, String> CODE = createField("code", org.jooq.impl.SQLDataType.CHAR.length(5).nullable(false), this, "");

	/**
	 * The column <code>public.films.title</code>.
	 */
	public final TableField<FilmsRecord, String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR.length(40).nullable(false), this, "");

	/**
	 * The column <code>public.films.did</code>.
	 */
	public final TableField<FilmsRecord, Integer> DID = createField("did", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>public.films.date_prod</code>.
	 */
	public final TableField<FilmsRecord, Date> DATE_PROD = createField("date_prod", org.jooq.impl.SQLDataType.DATE, this, "");

	/**
	 * The column <code>public.films.kind</code>.
	 */
	public final TableField<FilmsRecord, String> KIND = createField("kind", org.jooq.impl.SQLDataType.VARCHAR.length(10), this, "");

	/**
	 * The column <code>public.films.len</code>.
	 */
	public final TableField<FilmsRecord, Object> LEN = createField("len", org.jooq.impl.DefaultDataType.getDefaultDataType("interval"), this, "");

	/**
	 * Create a <code>public.films</code> table reference
	 */
	public Films() {
		this("films", null);
	}

	/**
	 * Create an aliased <code>public.films</code> table reference
	 */
	public Films(String alias) {
		this(alias, FILMS);
	}

	private Films(String alias, Table<FilmsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Films(String alias, Table<FilmsRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<FilmsRecord> getPrimaryKey() {
		return Keys.FIRSTKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<FilmsRecord>> getKeys() {
		return Arrays.<UniqueKey<FilmsRecord>>asList(Keys.FIRSTKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Films as(String alias) {
		return new Films(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Films rename(String name) {
		return new Films(name, null);
	}
}
