/*
 * This file is generated by jOOQ.
 */
package io.heapy.crm.komodo.store.postgres.keys


import io.heapy.crm.komodo.store.postgres.tables.FlywaySchemaHistory
import io.heapy.crm.komodo.store.postgres.tables.records.FlywaySchemaHistoryRecord

import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val FLYWAY_SCHEMA_HISTORY_PK: UniqueKey<FlywaySchemaHistoryRecord> = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("flyway_schema_history_pk"), arrayOf(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK), true)
