/**
 * This class is generated by jOOQ
 */
package by.heap.dao.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Date;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Films implements Serializable {

	private static final long serialVersionUID = 182053016;

	private String  code;
	private String  title;
	private Integer did;
	private Date    dateProd;
	private String  kind;
	private Object  len;

	public Films() {}

	public Films(Films value) {
		this.code = value.code;
		this.title = value.title;
		this.did = value.did;
		this.dateProd = value.dateProd;
		this.kind = value.kind;
		this.len = value.len;
	}

	public Films(
		String  code,
		String  title,
		Integer did,
		Date    dateProd,
		String  kind,
		Object  len
	) {
		this.code = code;
		this.title = title;
		this.did = did;
		this.dateProd = dateProd;
		this.kind = kind;
		this.len = len;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Integer getDid() {
		return this.did;
	}

	public void setDid(Integer did) {
		this.did = did;
	}

	public Date getDateProd() {
		return this.dateProd;
	}

	public void setDateProd(Date dateProd) {
		this.dateProd = dateProd;
	}

	public String getKind() {
		return this.kind;
	}

	public void setKind(String kind) {
		this.kind = kind;
	}

	public Object getLen() {
		return this.len;
	}

	public void setLen(Object len) {
		this.len = len;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Films (");

		sb.append(code);
		sb.append(", ").append(title);
		sb.append(", ").append(did);
		sb.append(", ").append(dateProd);
		sb.append(", ").append(kind);
		sb.append(", ").append(len);

		sb.append(")");
		return sb.toString();
	}
}
