/**
 * This class is generated by jOOQ
 */
package by.heap.dao.jooq.tables.records;


import by.heap.dao.jooq.tables.Films;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FilmsRecord extends UpdatableRecordImpl<FilmsRecord> implements Record6<String, String, Integer, Date, String, Object> {

	private static final long serialVersionUID = -1301641269;

	/**
	 * Setter for <code>public.films.code</code>.
	 */
	public void setCode(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.films.code</code>.
	 */
	public String getCode() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>public.films.title</code>.
	 */
	public void setTitle(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.films.title</code>.
	 */
	public String getTitle() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>public.films.did</code>.
	 */
	public void setDid(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.films.did</code>.
	 */
	public Integer getDid() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>public.films.date_prod</code>.
	 */
	public void setDateProd(Date value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.films.date_prod</code>.
	 */
	public Date getDateProd() {
		return (Date) getValue(3);
	}

	/**
	 * Setter for <code>public.films.kind</code>.
	 */
	public void setKind(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.films.kind</code>.
	 */
	public String getKind() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>public.films.len</code>.
	 */
	public void setLen(Object value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.films.len</code>.
	 */
	public Object getLen() {
		return (Object) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<String, String, Integer, Date, String, Object> fieldsRow() {
		return (Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<String, String, Integer, Date, String, Object> valuesRow() {
		return (Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return Films.FILMS.CODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Films.FILMS.TITLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return Films.FILMS.DID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field4() {
		return Films.FILMS.DATE_PROD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Films.FILMS.KIND;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Object> field6() {
		return Films.FILMS.LEN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getCode();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getTitle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getDid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value4() {
		return getDateProd();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getKind();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Object value6() {
		return getLen();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FilmsRecord value1(String value) {
		setCode(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FilmsRecord value2(String value) {
		setTitle(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FilmsRecord value3(Integer value) {
		setDid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FilmsRecord value4(Date value) {
		setDateProd(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FilmsRecord value5(String value) {
		setKind(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FilmsRecord value6(Object value) {
		setLen(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FilmsRecord values(String value1, String value2, Integer value3, Date value4, String value5, Object value6) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached FilmsRecord
	 */
	public FilmsRecord() {
		super(Films.FILMS);
	}

	/**
	 * Create a detached, initialised FilmsRecord
	 */
	public FilmsRecord(String code, String title, Integer did, Date dateProd, String kind, Object len) {
		super(Films.FILMS);

		setValue(0, code);
		setValue(1, title);
		setValue(2, did);
		setValue(3, dateProd);
		setValue(4, kind);
		setValue(5, len);
	}
}
